### ISSUE TITLE
The test suite doesn't build

### ISSUE THREAD

**Issue by meditans** [EduardSergeev/monad-memo#1]
Hi, I get some errors when building the test suite of this package. If you plan on fixing this, I could give you more details :)

**Comment by EduardSergeev** [comment]
Yes, please give me more detail on this. Still builds for me (with GHC 7.8.3).

**Comment by meditans** [comment]
Ok, I didn't remember the issue, so I checked it again. It seems that you simply need:

```
{-# LANGUAGE FlexibleContexts #-}
```

in your `test/MemoTest.hs` (for the type signature of `fibm` et al.). With that, the test suite also works on GHC 7.10.2.
