### ISSUE TITLE
Include in stackage

### ISSUE THREAD

**Issue by lspitzner** [EduardSergeev/monad-memo#2]
I'd like to see this package on stackage to allow including `brittany`, which depends on this.

Also, thanks for providing this package!

**Comment by EduardSergeev** [comment]
I believe this is now [done](https://github.com/commercialhaskell/stackage/commit/784420265af580f94b5775aabba3e35b160ca516#diff-b42a893675b90dbfa12fe0ce6064f0baR1595)? Though it seems to be nested under @tfausak - I might re-add it under my name if it makes more sense.

**Comment by tfausak** [comment]
Adding it under your name would be nice, but I don't mind having it under mine.

**Comment by EduardSergeev** [comment]
Adding it under my name: https://github.com/commercialhaskell/stackage/pull/3887
